import { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

/**
 * Builds and mounts the OpenAPI/Swagger document.
 *
 *  - /api-docs       Swagger UI (interactive try-it)
 *  - /api-docs-json  raw OpenAPI 3.0 spec (for client codegen,
 *                    Postman import, CI contract tests)
 *
 * Both paths live outside the /api/v1 prefix so they are independent of
 * the versioned API surface.
 *
 * Security posture: the spec is exposed without auth. If a deployment does
 * not want the contract public, gate /api-docs* at the ingress / reverse
 * proxy (basic auth, VPN, or an internal-only route).
 */
export function mountOpenApi(app: INestApplication, appBaseUrl?: string): void {
  const config = new DocumentBuilder()
    .setTitle('Anaqat Al-Iraq Backend API')
    .setDescription(
      [
        'Multi-tenant clothing-store backend.',
        '',
        'Auth: all endpoints under `/api/v1` except `POST /auth/login`,',
        '`POST /auth/register`, `POST /stores`, `GET /stores`, `GET /stores/:id`',
        'require a JWT via the `Authorization: Bearer <token>` header.',
        '',
        'Roles enforced via RolesGuard:',
        '  OWNER            — full access within the store',
        '  MANAGER          — user + inventory management, reports',
        '  INVENTORY_STAFF  — inventory CRUD',
        '  SALES_STAFF      — sales + read-only inventory',
        '',
        'Every response carries an `x-request-id` header echoed from the',
        'caller or generated by the server — include it in bug reports.',
      ].join('\n'),
    )
    .setVersion('1.0')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'Obtain a token from POST /api/v1/auth/login',
      },
      'bearer',
    )
    .addTag('auth', 'Login and first-user bootstrap')
    .addTag('stores', 'Tenant management')
    .addTag('users', 'Per-store user management (OWNER/MANAGER)')
    .addTag('inventory', 'Clothing items, sizes, and stock')
    .addTag('sales', 'Sale transactions and reports')
    .addTag('health', 'Liveness / readiness probe')
    .addTag('metrics', 'Prometheus scrape endpoint');

  if (appBaseUrl) {
    config.addServer(appBaseUrl, 'Configured APP_BASE_URL');
  }
  config.addServer('http://localhost:3000', 'Local development');

  const document = SwaggerModule.createDocument(app, config.build());

  SwaggerModule.setup('api-docs', app, document, {
    swaggerOptions: {
      persistAuthorization: true,
      tryItOutEnabled: true,
      displayRequestDuration: true,
    },
  });
}
